#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

/// <summary>
/// Editor helper for the FarmingSim project.
/// After importing the recommended free Asset Store packages, run:
/// Tools -> FarmingSim -> Apply Imported Visual Assets
///
/// It tries to wire imported free assets to the existing project without changing gameplay scripts:
/// - soil materials on GardenTile objects
/// - plant growth prefab slots on PlantData assets
/// - visual well model as child of WaterWell
/// - character visuals under Player and SellerNPC
/// - Rain Maker prefab into WeatherSystem / GG_Step4SceneBootstrap
///
/// Safe by design: it keeps original gameplay objects, colliders and scripts in place.
/// </summary>
public static class FarmingSimAssetStoreApplicator
{
    private const string AutoFolder = "Assets/Art/AutoGeneratedFallbacks";
    private const string AutoMaterialsFolder = AutoFolder + "/Materials";
    private const string AutoPrefabsFolder = AutoFolder + "/PlantPrefabs";

    [MenuItem("Tools/FarmingSim/Apply Imported Visual Assets")]
    public static void ApplyImportedVisualAssets()
    {
        ApplyImportedVisualAssets(showDialog: true);
    }

    public static void ApplyImportedVisualAssetsBatch()
    {
        const string scenePath = "Assets/Scenes/SampleScene.unity";
        if (AssetDatabase.LoadAssetAtPath<SceneAsset>(scenePath) != null)
            EditorSceneManager.OpenScene(scenePath);

        ApplyImportedVisualAssets(showDialog: false);
        EditorApplication.Exit(0);
    }

    private static void ApplyImportedVisualAssets(bool showDialog)
    {
        EnsureFolders();

        int changed = 0;
        var report = new List<string>();

        changed += ConvertImportedMaterialsToUrp(report);
        changed += ApplyTerrainMaterial(report);
        changed += ApplySoilMaterials(report);
        changed += ApplyWellVisual(report);
        changed += ApplyCharacterVisuals(report);
        changed += ApplyRainSystem(report);
        changed += ApplyPlantDataPrefabs(report);
        changed += ApplyExistingRendererMaterials(report);

        EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());
        AssetDatabase.SaveAssets();
        EditorSceneManager.SaveOpenScenes();

        string msg = "FarmingSim visual assets applied. Changes: " + changed + "\n\n" + string.Join("\n", report);
        Debug.Log(msg);
        if (showDialog && !Application.isBatchMode)
            EditorUtility.DisplayDialog("FarmingSim", msg, "OK");
    }

    [MenuItem("Tools/FarmingSim/Generate Fallback Visuals Only")]
    public static void GenerateFallbacksOnly()
    {
        EnsureFolders();
        CreateFallbackMaterials();
        CreateFallbackPlantPrefabs();
        AssetDatabase.SaveAssets();
        EditorUtility.DisplayDialog("FarmingSim", "Fallback materials and plant prefabs generated in:\n" + AutoFolder, "OK");
    }

    private static int ApplySoilMaterials(List<string> report)
    {
        var unplowed = AssetDatabase.LoadAssetAtPath<Material>("Assets/Materials/NormalSoil.mat") ?? FindBestMaterial(
            requiredAny: new[] { "soil", "dirt", "ground", "earth", "mud", "grass" },
            niceToHave: new[] { "yughues", "nature", "ground", "free" },
            negative: new[] { "snow", "water", "leaf", "foliage" }) ?? GetOrCreateFallbackMaterial("FS_UnplowedSoil", new Color(0.31f, 0.20f, 0.11f));

        var plowed = AssetDatabase.LoadAssetAtPath<Material>("Assets/Materials/PlowedSoil.mat") ?? FindBestMaterial(
            requiredAny: new[] { "plowed", "tilled", "field", "dirt", "soil", "mud", "clay" },
            niceToHave: new[] { "yughues", "ground", "soil" },
            negative: new[] { "snow", "water", "leaf", "foliage" }) ?? GetOrCreateFallbackMaterial("FS_PlowedSoil", new Color(0.20f, 0.11f, 0.055f));

        int count = 0;
        foreach (var tile in FindSceneObjects<GardenTile>())
        {
            if (tile.soilRenderer == null) tile.soilRenderer = tile.GetComponent<MeshRenderer>();
            tile.unplowedMat = unplowed;
            tile.plowedMat = plowed;
            if (tile.soilRenderer != null)
            {
                tile.soilRenderer.sharedMaterial = tile.state == TileState.Unplowed ? unplowed : plowed;
                EditorUtility.SetDirty(tile.soilRenderer);
            }
            EditorUtility.SetDirty(tile);
            count++;
        }

        var gardenBase = GameObject.Find("Garden");
        var gardenBaseRenderer = gardenBase != null ? gardenBase.GetComponent<MeshRenderer>() : null;
        if (gardenBaseRenderer != null)
        {
            gardenBaseRenderer.sharedMaterial = unplowed;
            EditorUtility.SetDirty(gardenBaseRenderer);
        }

        report.Add("Soil: assigned " + unplowed.name + " / " + plowed.name + " to " + count + " GardenTile objects" + (gardenBaseRenderer != null ? " and the Garden base." : "."));
        return count;
    }

    private static int ApplyTerrainMaterial(List<string> report)
    {
        var terrainMaterial = AssetDatabase.LoadAssetAtPath<Material>("Assets/Materials/URP_TerrainLit.mat");
        if (terrainMaterial == null)
        {
            report.Add("Terrain: URP_TerrainLit material was not found.");
            return 0;
        }

        int changed = 0;
        foreach (var terrain in UnityEngine.Object.FindObjectsOfType<Terrain>(true))
        {
            if (terrain.materialTemplate == terrainMaterial) continue;
            terrain.materialTemplate = terrainMaterial;
            EditorUtility.SetDirty(terrain);
            changed++;
        }

        report.Add("Terrain: assigned URP terrain material to " + changed + " Terrain objects.");
        return changed;
    }

    private static int ApplyWellVisual(List<string> report)
    {
        var well = GameObject.Find("WaterWell") ?? FindByNameContains("well");
        if (well == null)
        {
            report.Add("Well: no WaterWell object found in active scene.");
            return 0;
        }

        var prefab = FindBestGameObjectAsset(
            requiredAny: new[] { "well", "waterwell", "water well" },
            niceToHave: new[] { "old", "water", "stone", "prefab" },
            negative: new[] { "demo", "example", "scene" });

        if (prefab == null)
        {
            ApplyMaterialToRenderers(well, FindBestMaterial(new[] { "stone", "rock", "wall", "ground" }, new[] { "yughues", "stone" }, new[] { "water", "leaf" }) ?? GetOrCreateFallbackMaterial("FS_WellStone", new Color(0.43f, 0.42f, 0.38f)));
            report.Add("Well: no imported well prefab found; applied stone material to existing WaterWell renderers.");
            return 1;
        }

        RemoveChildrenByPrefix(well.transform, "ImportedVisual_");
        var instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab, well.scene);
        instance.name = "ImportedVisual_" + prefab.name;
        instance.transform.SetParent(well.transform, false);
        instance.transform.localPosition = Vector3.zero;
        instance.transform.localRotation = Quaternion.identity;
        instance.transform.localScale = Vector3.one;

        DisableRenderersOnly(well, exceptChildPrefix: "ImportedVisual_");
        EditorUtility.SetDirty(well);
        report.Add("Well: added imported visual prefab " + prefab.name + " under WaterWell.");
        return 1;
    }

    private static int ApplyCharacterVisuals(List<string> report)
    {
        int changes = 0;
        var fallbackCharacterPrefab = FindBestGameObjectAsset(
            requiredAny: new[] { "character", "human", "humanoid", "male", "person" },
            niceToHave: new[] { "lowpoly", "low poly", "free", "npc" },
            negative: new[] { "animation", "demo", "scene", "controller" });

        var playerPrefab = LoadFirstPrefab(
            "Assets/FreeCharacter/Prefabs/Lumberjack1.prefab",
            "Assets/FreeCharacter/Prefabs/Lumberjack2.prefab",
            "Assets/FreeCharacter/Prefabs/Lumberjack3.prefab") ?? fallbackCharacterPrefab;

        var sellerPrefab = LoadFirstPrefab(
            "Assets/FreeCharacter/Prefabs/Lumberjack2.prefab",
            "Assets/FreeCharacter/Prefabs/Lumberjack3.prefab",
            "Assets/FreeCharacter/Prefabs/Lumberjack1.prefab") ?? fallbackCharacterPrefab;

        var cloth = FindBestMaterial(new[] { "cloth", "clothes", "fabric", "farmer", "character" }, new[] { "lowpoly", "free" }, new[] { "soil", "water", "stone" })
                   ?? GetOrCreateFallbackMaterial("FS_FarmerClothes", new Color(0.08f, 0.22f, 0.55f));

        var player = GameObject.Find("Player");
        if (player != null)
        {
            if (playerPrefab != null)
            {
                AddVisualChild(player, playerPrefab, "ImportedVisual_Player", new Vector3(0, -0.9f, 0), Quaternion.identity, Vector3.one * 1.35f);
                DisableRenderersOnly(player, exceptChildPrefix: "ImportedVisual_Player");
            }
            else ApplyMaterialToRenderers(player, cloth);
            report.Add(playerPrefab != null ? "Player: added character visual " + playerPrefab.name + " and hid primitive placeholder renderers." : "Player: no character prefab found; applied clothes material.");
            changes++;
        }
        else report.Add("Player: object named Player not found.");

        var npc = GameObject.Find("SellerNPC") ?? FindByNameContains("seller");
        if (npc != null)
        {
            NormalizeSellerRoot(npc);
            if (sellerPrefab != null)
            {
                AddVisualChild(npc, sellerPrefab, "ImportedVisual_SellerNPC", Vector3.zero, Quaternion.identity, Vector3.one * 1.35f);
                DisableRenderersOnly(npc, exceptChildPrefix: "ImportedVisual_SellerNPC");
            }
            else ApplyMaterialToRenderers(npc, cloth);
            report.Add(sellerPrefab != null ? "SellerNPC: added character visual " + sellerPrefab.name + " and hid primitive placeholder renderers." : "SellerNPC: no character prefab found; applied clothes material.");
            changes++;
        }
        else report.Add("SellerNPC: object named SellerNPC not found.");

        return changes;
    }

    private static int ApplyRainSystem(List<string> report)
    {
        var weather = UnityEngine.Object.FindObjectOfType<WeatherSystem>(true);
        var bootstrap = UnityEngine.Object.FindObjectOfType<GG_Step4SceneBootstrap>(true);

        var rainPrefab = FindBestGameObjectAsset(
            requiredAny: new[] { "rain" },
            niceToHave: new[] { "rainmaker", "particle", "weather", "3d" },
            negative: new[] { "demo", "example", "scene", "script" });

        GameObject rainObject = null;

        if (rainPrefab != null)
        {
            var parent = weather != null ? weather.transform : null;
            if (parent != null) RemoveChildrenByPrefix(parent, "ImportedVisual_Rain");
            var legacyRain = GameObject.Find("GG_RainParticles") ?? GameObject.Find("GG_Step4_RainParticles");
            if (legacyRain != null)
            {
                legacyRain.SetActive(false);
                EditorUtility.SetDirty(legacyRain);
            }

            rainObject = (GameObject)PrefabUtility.InstantiatePrefab(rainPrefab, SceneManager.GetActiveScene());
            rainObject.name = "ImportedVisual_RainMaker";
            if (parent != null) rainObject.transform.SetParent(parent, false);
            rainObject.transform.localPosition = new Vector3(0, 8, 0);
            rainObject.transform.localRotation = Quaternion.identity;
            rainObject.transform.localScale = Vector3.one;
            rainObject.SetActive(false);
        }
        else
        {
            rainObject = GameObject.Find("GG_RainParticles") ?? FindByNameContains("rain");
            var rainMat = FindBestMaterial(new[] { "rain", "drop", "water" }, new[] { "rainmaker", "particle" }, new[] { "soil", "stone" })
                          ?? GetOrCreateFallbackMaterial("FS_RainDrops", new Color(0.55f, 0.75f, 1.0f, 0.6f));
            if (rainObject != null) ApplyMaterialToRenderers(rainObject, rainMat);
        }

        if (weather != null && rainObject != null)
        {
            weather.rainParticles = rainObject;
            if (weather.sunLight == null) weather.sunLight = UnityEngine.Object.FindObjectOfType<Light>(true);
            EditorUtility.SetDirty(weather);
        }

        if (bootstrap != null && rainObject != null)
        {
            bootstrap.rainParticles = rainObject;
            if (bootstrap.sceneSun == null) bootstrap.sceneSun = UnityEngine.Object.FindObjectOfType<Light>(true);
            EditorUtility.SetDirty(bootstrap);
        }

        report.Add(rainObject != null ? "Weather: assigned rain object " + rainObject.name + "." : "Weather: no rain prefab/object found.");
        return rainObject != null ? 1 : 0;
    }

    private static int ApplyPlantDataPrefabs(List<string> report)
    {
        CreateFallbackPlantPrefabs();

        int changed = 0;
        var plantGuids = AssetDatabase.FindAssets("t:PlantData");
        if (plantGuids.Length == 0)
        {
            report.Add("Plants: no PlantData assets found. Open the full project, not only the small zip, then run again.");
            return 0;
        }

        foreach (string guid in plantGuids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            var plant = AssetDatabase.LoadAssetAtPath<PlantData>(path);
            if (plant == null) continue;

            string p = (plant.plantName ?? plant.name).ToLowerInvariant();
            var explicitGrowing = GetExplicitImportedCropPrefab(p);
            var explicitRipe = GetExplicitImportedCropPrefab(p);
            var seedling = FindBestGameObjectAsset(new[] { p, "seedling", "sprout" }, new[] { "farm", "plant", "vegetable" }, new[] { "scene", "demo" })
                           ?? plant.seedlingPrefab
                           ?? LoadFallbackPrefab("Generic_Seedling.prefab");
            var growing = explicitGrowing
                          ?? FindBestGameObjectAsset(new[] { p, "growing", "plant" }, new[] { "farm", "vegetable" }, new[] { "scene", "demo" })
                          ?? plant.growingPrefab
                          ?? LoadFallbackPrefab("Generic_Growing.prefab");
            var ripe = explicitRipe
                       ?? FindBestGameObjectAsset(new[] { p, "ripe", "harvest", "crop", "vegetable" }, new[] { "farm", "plant" }, new[] { "scene", "demo" })
                       ?? plant.ripePrefab
                       ?? LoadFallbackPrefab("Generic_Ripe.prefab");
            var rotten = FindBestGameObjectAsset(new[] { "dead", "rotten", "wither", "dry" }, new[] { p, "plant" }, new[] { "scene", "demo" })
                         ?? plant.rottingPrefab
                         ?? LoadFallbackPrefab("Generic_Rotting.prefab");

            bool did = false;
            if (seedling != null && plant.seedlingPrefab != seedling) { plant.seedlingPrefab = seedling; did = true; }
            if (growing != null && plant.growingPrefab != growing) { plant.growingPrefab = growing; did = true; }
            if (ripe != null && plant.ripePrefab != ripe) { plant.ripePrefab = ripe; did = true; }
            if (rotten != null && plant.rottingPrefab != rotten) { plant.rottingPrefab = rotten; did = true; }

            if (did)
            {
                EditorUtility.SetDirty(plant);
                changed++;
            }
        }

        report.Add("Plants: assigned growth prefabs to " + changed + " PlantData assets. If imported crop prefabs were not found, fallback prefabs were used.");
        return changed;
    }

    private static GameObject GetExplicitImportedCropPrefab(string plantName)
    {
        if (plantName.Contains("tomato"))
            return LoadFirstPrefab("Assets/LowPolyFarmLite/Prefabs/TomatoPlant_01.prefab");

        if (plantName.Contains("lettuce"))
            return LoadFirstPrefab("Assets/LowPolyFarmLite/Prefabs/Cabbage_01.prefab");

        return null;
    }

    private static int ApplyExistingRendererMaterials(List<string> report)
    {
        int changed = 0;
        var leaf = FindBestMaterial(new[] { "leaf", "foliage", "grass", "plant", "green" }, new[] { "yughues", "nature" }, new[] { "soil", "stone", "water" })
                   ?? GetOrCreateFallbackMaterial("FS_Leaves", new Color(0.13f, 0.55f, 0.18f));
        var water = FindBestMaterial(new[] { "water" }, new[] { "yughues", "nature" }, new[] { "soil", "stone" })
                    ?? GetOrCreateFallbackMaterial("FS_Water", new Color(0.1f, 0.45f, 0.9f, 0.75f));
        var stone = FindBestMaterial(new[] { "stone", "rock" }, new[] { "yughues", "ground" }, new[] { "water", "leaf" })
                    ?? GetOrCreateFallbackMaterial("FS_Stone", new Color(0.43f, 0.42f, 0.38f));

        foreach (var r in UnityEngine.Object.FindObjectsOfType<Renderer>(true))
        {
            if (IsUnderPrefix(r.transform, "ImportedVisual_"))
                continue;

            string n = r.gameObject.name.ToLowerInvariant();
            if (n.Contains("well") || n.Contains("stone") || n.Contains("fountain")) { r.sharedMaterial = stone; changed++; EditorUtility.SetDirty(r); }
            else if (n.Contains("water")) { r.sharedMaterial = water; changed++; EditorUtility.SetDirty(r); }
            else if (n.Contains("tomato") || n.Contains("carrot") || n.Contains("lettuce") || n.Contains("plant") || n.Contains("leaf")) { r.sharedMaterial = leaf; changed++; EditorUtility.SetDirty(r); }
        }

        report.Add("Existing renderers: applied nature/water/stone materials to " + changed + " named renderers where possible.");
        return changed;
    }

    private static int ConvertImportedMaterialsToUrp(List<string> report)
    {
        Shader lit = Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Universal Render Pipeline/Simple Lit");
        Shader particle = Shader.Find("Universal Render Pipeline/Particles/Unlit") ?? Shader.Find("Universal Render Pipeline/Unlit") ?? lit;
        if (lit == null)
        {
            report.Add("Materials: URP shader not found; no material conversion was performed.");
            return 0;
        }

        string[] folders =
        {
            "Assets/FreeCharacter",
            "Assets/Old Water Well",
            "Assets/LowPolyFarmLite",
            "Assets/BrokenVector",
            "Assets/ThreeBox",
            "Assets/YughuesFreeGroundMaterials",
            "Assets/YughuesFreeNatureMaterials",
            "Assets/Handpainted_Grass_and_Ground_Textures",
            "Assets/RainMaker"
        };

        var validFolders = folders.Where(AssetDatabase.IsValidFolder).ToArray();
        int changed = 0;

        foreach (string guid in AssetDatabase.FindAssets("t:Material", validFolders))
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            var mat = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (mat == null || mat.shader == null) continue;

            string shaderName = mat.shader.name;
            bool isParticle = path.IndexOf("/RainMaker/", StringComparison.OrdinalIgnoreCase) >= 0 ||
                              shaderName.IndexOf("particle", StringComparison.OrdinalIgnoreCase) >= 0;

            if (!isParticle && shaderName.StartsWith("Universal Render Pipeline", StringComparison.OrdinalIgnoreCase))
                continue;

            Texture mainTexture = GetMaterialTexture(mat, "_BaseMap") ?? GetMaterialTexture(mat, "_BaseColorMap") ?? GetMaterialTexture(mat, "_MainTex") ?? mat.mainTexture;
            Texture normalTexture = GetMaterialTexture(mat, "_BumpMap") ?? GetMaterialTexture(mat, "_NormalMap");
            Texture metallicTexture = GetMaterialTexture(mat, "_MetallicGlossMap");
            Color color = mat.HasProperty("_BaseColor") ? mat.GetColor("_BaseColor") :
                          mat.HasProperty("_Color") ? mat.GetColor("_Color") : Color.white;

            mat.shader = isParticle ? particle : lit;
            SetTextureIfExists(mat, "_BaseMap", mainTexture);
            SetTextureIfExists(mat, "_MainTex", mainTexture);
            SetColorIfExists(mat, "_BaseColor", color);
            SetColorIfExists(mat, "_Color", color);

            if (normalTexture != null)
            {
                SetTextureIfExists(mat, "_BumpMap", normalTexture);
                mat.EnableKeyword("_NORMALMAP");
            }

            if (metallicTexture != null)
            {
                SetTextureIfExists(mat, "_MetallicGlossMap", metallicTexture);
                mat.EnableKeyword("_METALLICSPECGLOSSMAP");
            }

            if (isParticle)
            {
                SetFloatIfExists(mat, "_Surface", 1f);
                SetFloatIfExists(mat, "_Blend", 0f);
                SetFloatIfExists(mat, "_SrcBlend", 5f);
                SetFloatIfExists(mat, "_DstBlend", 10f);
                SetFloatIfExists(mat, "_SrcBlendAlpha", 1f);
                SetFloatIfExists(mat, "_DstBlendAlpha", 10f);
                SetFloatIfExists(mat, "_ZWrite", 0f);
                mat.SetOverrideTag("RenderType", "Transparent");
                mat.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");
                mat.renderQueue = 3000;
            }

            EditorUtility.SetDirty(mat);
            changed++;
        }

        report.Add("Materials: converted " + changed + " imported materials to URP-compatible shaders.");
        return changed;
    }

    private static Texture GetMaterialTexture(Material mat, string property)
    {
        return mat.HasProperty(property) ? mat.GetTexture(property) : null;
    }

    private static void SetTextureIfExists(Material mat, string property, Texture texture)
    {
        if (texture != null && mat.HasProperty(property)) mat.SetTexture(property, texture);
    }

    private static void SetColorIfExists(Material mat, string property, Color color)
    {
        if (mat.HasProperty(property)) mat.SetColor(property, color);
    }

    private static void SetFloatIfExists(Material mat, string property, float value)
    {
        if (mat.HasProperty(property)) mat.SetFloat(property, value);
    }

    private static void AddVisualChild(GameObject parent, GameObject prefab, string childName, Vector3 localPos, Quaternion localRot, Vector3 localScale)
    {
        RemoveChildrenByPrefix(parent.transform, childName);
        var instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab, parent.scene);
        instance.name = childName;
        instance.transform.SetParent(parent.transform, false);
        instance.transform.localPosition = localPos;
        instance.transform.localRotation = localRot;
        instance.transform.localScale = localScale;
        EditorUtility.SetDirty(instance);
        EditorUtility.SetDirty(parent);
    }

    private static GameObject LoadFirstPrefab(params string[] paths)
    {
        foreach (string path in paths)
        {
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
            if (prefab != null) return prefab;
        }

        return null;
    }

    private static void NormalizeSellerRoot(GameObject npc)
    {
        npc.transform.localScale = Vector3.one;

        var sphere = npc.GetComponent<SphereCollider>();
        if (sphere != null)
        {
            sphere.radius = Mathf.Max(sphere.radius, 1.2f);
            sphere.center = new Vector3(0f, 0.5f, 0f);
            EditorUtility.SetDirty(sphere);
        }

        EditorUtility.SetDirty(npc.transform);
    }

    private static void DisableRenderersOnly(GameObject root, string exceptChildPrefix)
    {
        foreach (var r in root.GetComponentsInChildren<Renderer>(true))
        {
            if (r.gameObject.name.StartsWith(exceptChildPrefix, StringComparison.OrdinalIgnoreCase) || IsUnderPrefix(r.transform, exceptChildPrefix))
                continue;
            r.enabled = false;
            EditorUtility.SetDirty(r);
        }
    }

    private static bool IsUnderPrefix(Transform t, string prefix)
    {
        while (t != null)
        {
            if (t.name.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)) return true;
            t = t.parent;
        }
        return false;
    }

    private static void RemoveChildrenByPrefix(Transform parent, string prefix)
    {
        var toDelete = new List<GameObject>();
        foreach (Transform child in parent)
            if (child.name.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)) toDelete.Add(child.gameObject);
        foreach (var go in toDelete) UnityEngine.Object.DestroyImmediate(go);
    }

    private static void ApplyMaterialToRenderers(GameObject root, Material mat)
    {
        if (root == null || mat == null) return;
        foreach (var r in root.GetComponentsInChildren<Renderer>(true))
        {
            r.sharedMaterial = mat;
            EditorUtility.SetDirty(r);
        }
    }

    private static Material FindBestMaterial(string[] requiredAny, string[] niceToHave, string[] negative)
    {
        return FindBestAsset<Material>(new[] { "t:Material" }, requiredAny, niceToHave, negative);
    }

    private static GameObject FindBestGameObjectAsset(string[] requiredAny, string[] niceToHave, string[] negative)
    {
        var prefab = FindBestAsset<GameObject>(new[] { "t:Prefab" }, requiredAny, niceToHave, negative);
        if (prefab != null) return prefab;
        return FindBestAsset<GameObject>(new[] { "t:Model" }, requiredAny, niceToHave, negative);
    }

    private static T FindBestAsset<T>(string[] filters, string[] requiredAny, string[] niceToHave, string[] negative) where T : UnityEngine.Object
    {
        var candidates = new List<(T asset, int score, string path)>();
        var seen = new HashSet<string>();

        foreach (var filter in filters)
        {
            foreach (string guid in AssetDatabase.FindAssets(filter))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (!seen.Add(path)) continue;
                string hay = (path + " " + System.IO.Path.GetFileNameWithoutExtension(path)).ToLowerInvariant();

                if (negative != null && negative.Any(t => hay.Contains(t.ToLowerInvariant()))) continue;

                int requiredHits = requiredAny == null ? 1 : requiredAny.Count(t => hay.Contains(t.ToLowerInvariant()));
                if (requiredAny != null && requiredAny.Length > 0 && requiredHits == 0) continue;

                int score = requiredHits * 10;
                if (niceToHave != null) score += niceToHave.Count(t => hay.Contains(t.ToLowerInvariant())) * 3;
                if (hay.Contains("yughues")) score += 3;
                if (hay.Contains("rainmaker")) score += 3;
                if (hay.Contains("lowpoly") || hay.Contains("low poly")) score += 2;
                if (hay.Contains("prefab")) score += 2;

                var asset = AssetDatabase.LoadAssetAtPath<T>(path);
                if (asset != null) candidates.Add((asset, score, path));
            }
        }

        return candidates.OrderByDescending(c => c.score).ThenBy(c => c.path.Length).Select(c => c.asset).FirstOrDefault();
    }

    private static GameObject FindByNameContains(string token)
    {
        token = token.ToLowerInvariant();
        foreach (var t in UnityEngine.Object.FindObjectsOfType<Transform>(true))
            if (t.name.ToLowerInvariant().Contains(token)) return t.gameObject;
        return null;
    }

    private static T[] FindSceneObjects<T>() where T : UnityEngine.Object
    {
        return UnityEngine.Object.FindObjectsOfType<T>(true);
    }

    private static void EnsureFolders()
    {
        EnsureFolder("Assets", "Art");
        EnsureFolder("Assets/Art", "AutoGeneratedFallbacks");
        EnsureFolder(AutoFolder, "Materials");
        EnsureFolder(AutoFolder, "PlantPrefabs");
    }

    private static void EnsureFolder(string parent, string child)
    {
        string full = parent + "/" + child;
        if (!AssetDatabase.IsValidFolder(full)) AssetDatabase.CreateFolder(parent, child);
    }

    private static void CreateFallbackMaterials()
    {
        GetOrCreateFallbackMaterial("FS_UnplowedSoil", new Color(0.31f, 0.20f, 0.11f));
        GetOrCreateFallbackMaterial("FS_PlowedSoil", new Color(0.20f, 0.11f, 0.055f));
        GetOrCreateFallbackMaterial("FS_Leaves", new Color(0.13f, 0.55f, 0.18f));
        GetOrCreateFallbackMaterial("FS_RipeVegetable", new Color(0.85f, 0.12f, 0.08f));
        GetOrCreateFallbackMaterial("FS_RottingPlant", new Color(0.25f, 0.18f, 0.08f));
        GetOrCreateFallbackMaterial("FS_Water", new Color(0.1f, 0.45f, 0.9f, 0.75f));
        GetOrCreateFallbackMaterial("FS_Stone", new Color(0.43f, 0.42f, 0.38f));
        GetOrCreateFallbackMaterial("FS_FarmerClothes", new Color(0.08f, 0.22f, 0.55f));
        GetOrCreateFallbackMaterial("FS_RainDrops", new Color(0.55f, 0.75f, 1.0f, 0.6f));
    }

    private static Material GetOrCreateFallbackMaterial(string name, Color color)
    {
        EnsureFolders();
        string path = AutoMaterialsFolder + "/" + name + ".mat";
        var mat = AssetDatabase.LoadAssetAtPath<Material>(path);
        if (mat != null) return mat;

        Shader shader = Shader.Find("Universal Render Pipeline/Lit");
        if (shader == null) shader = Shader.Find("Standard");
        mat = new Material(shader) { name = name, color = color };
        if (mat.HasProperty("_BaseColor")) mat.SetColor("_BaseColor", color);
        if (mat.HasProperty("_Color")) mat.SetColor("_Color", color);
        AssetDatabase.CreateAsset(mat, path);
        return mat;
    }

    private static void CreateFallbackPlantPrefabs()
    {
        CreateFallbackMaterials();
        CreatePrimitivePrefab("Generic_Seedling", PrimitiveType.Cylinder, GetOrCreateFallbackMaterial("FS_Leaves", new Color(0.13f, 0.55f, 0.18f)), new Vector3(0.15f, 0.35f, 0.15f));
        CreatePrimitivePrefab("Generic_Growing", PrimitiveType.Capsule, GetOrCreateFallbackMaterial("FS_Leaves", new Color(0.13f, 0.55f, 0.18f)), new Vector3(0.25f, 0.55f, 0.25f));
        CreatePrimitivePrefab("Generic_Ripe", PrimitiveType.Sphere, GetOrCreateFallbackMaterial("FS_RipeVegetable", new Color(0.85f, 0.12f, 0.08f)), new Vector3(0.35f, 0.35f, 0.35f));
        CreatePrimitivePrefab("Generic_Rotting", PrimitiveType.Capsule, GetOrCreateFallbackMaterial("FS_RottingPlant", new Color(0.25f, 0.18f, 0.08f)), new Vector3(0.25f, 0.35f, 0.25f));
    }

    private static GameObject LoadFallbackPrefab(string fileName)
    {
        return AssetDatabase.LoadAssetAtPath<GameObject>(AutoPrefabsFolder + "/" + fileName);
    }

    private static void CreatePrimitivePrefab(string name, PrimitiveType type, Material mat, Vector3 scale)
    {
        string path = AutoPrefabsFolder + "/" + name + ".prefab";
        if (AssetDatabase.LoadAssetAtPath<GameObject>(path) != null) return;

        var go = GameObject.CreatePrimitive(type);
        go.name = name;
        go.transform.localScale = scale;
        var renderer = go.GetComponent<Renderer>();
        if (renderer != null) renderer.sharedMaterial = mat;
        var collider = go.GetComponent<Collider>();
        if (collider != null) UnityEngine.Object.DestroyImmediate(collider);
        PrefabUtility.SaveAsPrefabAsset(go, path);
        UnityEngine.Object.DestroyImmediate(go);
    }
}
#endif
